// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:048fcc09-0ec3-4842-a108-3f34be11df97",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_FSVdrLZEl",
    "aws_user_pools_web_client_id": "3pusgjp2tq680s3eckp63e16mb",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://jowlfyzyd5dgzhv5ydjmv4dqzi.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
